# Generated by Django 3.1.2 on 2023-10-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_section_sectionposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='articles',
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
